plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

# TODO: change the yarn version if necessary, i.e. to berry
yarnPath: .yarn/releases/yarn-2.4.0.cjs

###
# FIXING ERROR
# middie tried to access Fastify, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
###
packageExtensions:
  middie@*:
    dependencies:
      fastify: "^3.9.1"