version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - mongodb:/data/db
  nested-prototype:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/nested
      PORT: 3000
volumes:
  mongodb: